name: Build and Deploy Jekyll with GitHub Actions

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  jekyll-gh-pages:
    uses: noraworld/github-actions-sandbox/.github/workflows/jekyll-gh-pages.yml@main
    with:
      # use_ruby_version: true
      use_gemfile: true
